[Settings]

#Layout
opacity = 80
timer_x = 270
timer_y = 165
table_x = 1910
table_y = 40
timer_x_2 = 270
timer_y_2 = 265
table_x_2 = 960
table_y_2 = 40
table_align = right
table_visible = 1
ai_count_visible = 1

#Font
timer_font_size = 16
label_font_size = 12
timer_font_color = lightcyan
timer_font_color_while_running = khaki
timer_font_color_ex = thistle
ai_count_font_color = white
outline_color = #101010

#Sound
play_start_sound = true
play_record_sound = true
play_bomb_sound = true
sound_volume = 50
sound_delay = 3250

#Hotkey
start_key = f12
log_key = home
log_key_ex = delete
log_key_loop = end
increment_key = page up
decrement_key = page down
ai_count_key_2 = f9
ai_count_key_3 = f10
sheet_switch_key = ctrl+shift+s
preset_switch_key = ctrl+shift+tab
reset_position_key = ctrl+shift+r


[Preset1]
name = ルベランギス3
table_file = ルベランギス3.xlsx

initial_time = 09:59
activation_normal = 60000
activation_ex  = 60000
activation_loopA  = 5000
activation_loopB  = 6000
loopA_time = 23500,21000
loopB_time = 22200,24500

log_label = 
log_label_ex = 
loopA_labels = 1 線上\nR90_A1.png,2 線上(遅)\nR90_A2.png,3 金網\nR90_B.png,4 線上(遅)\nR90_A1.png,5 外周\nR90_C.png,6 金網(遅)\nR90_B.png
loopB_labels = 1 虹床,2 外周\nR25_A.png,3 虹床,4 外周\nR25_B.png,5 虹床,6 なし\nR25_C.png,7 虹床,8 線上\nR25_D.png,9 虹床,10 金網\nR25E_.png,11 虹床,12 線外\nR25_F.png


[Preset2]
name = デルメゼ4
table_file = デルメゼ4.xlsx

initial_time = 19:59
activation_normal = 108500
activation_ex  = 60000
activation_loopA  = 5000
activation_loopB  = 6000
loopA_time = 14550
loopB_time = 12550

log_label = 
log_label_ex = 
loopA_labels = 
loopB_labels = 


